---
version: '3.8'
services:
  s3fs:
    privileged: true
    image: efrecon/s3fs
    restart: unless-stopped
    environment:
      - AWS_S3_URL=${S3_ENDPOINT_URL}
      - AWS_S3_BUCKET=${S3_BUCKET_NAME}
      - AWS_S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - UID=${UID}
      - GID=${GID}
      - S3FS_ARGS='-oallow_other'
      - S3FS_DEBUG=0
    volumes:
      - ${S3PATH}:/opt/s3fs/bucket:rshared
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined

