---
services:
  web:
    image: nginx:1.25
    restart: unless-stopped
    environment:
      - NGINX_HOST=${HOSTNAME}
      - NGINX_PORT=80
      - DNS=${DNS}
      - S3_ENDPOINT_HOSTNAME=${S3_ENDPOINT_HOSTNAME}
      - S3_ENDPOINT_PROTOCOL=${S3_ENDPOINT_PROTOCOL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_URBES_VIZ_BUCKET_NAME=${S3_URBES_VIZ_BUCKET_NAME}
    volumes:
      - ./nginxTemplates:/etc/nginx/templates
      - ./nginxCache:/etc/nginx/cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3fs-enacit4r-cdn.tls=true"
      - "traefik.http.routers.s3fs-enacit4r-cdn.rule=PathPrefix(`/`)"
      - "traefik.http.services.s3fs-enacit4r-cdn.loadbalancer.server.port=80"
  reverse-proxy:
    image: traefik:v2.5
    restart: unless-stopped
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/configuration/traefik.yml
      - /etc/ssl:/etc/ssl
    environment:
      - SSL_CERT_CRT=${SSL_CERT_CRT}
      - SSL_CERT_KEY=${SSL_CERT_KEY}
    ports:
      - "80:80"
      - "443:443"
