---
version: '3.8'
services:
  s3fs:
    privileged: true
    image: efrecon/s3fs
    restart: unless-stopped
    environment:
      - AWS_S3_URL=${S3_ENDPOINT_URL}
      - AWS_S3_BUCKET=${S3_BUCKET_NAME}
      - AWS_S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - UID=${S3_UID}
      - GID=${S3_GID}
      - S3FS_ARGS='-oallow_other'
      - S3FS_DEBUG=0
    volumes:
      - ${S3PATH}:/opt/s3fs/bucket:rshared
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined

  web:
    image: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=${HOSTNAME}
      - NGINX_PORT=80
    volumes:
      - ${S3PATH}:/data:rshared
      - ./nginxTemplates:/etc/nginx/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3fs-enacit4r-cdn.tls=true"
      - "traefik.http.routers.s3fs-enacit4r-cdn.rule=PathPrefix(`/`)"
      - "traefik.http.services.s3fs-enacit4r-cdn.loadbalancer.server.port=80"

  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSL_CERT_KEY:-./cert/certificate.key}:/cert/certificate.key
      - ${SSL_CERT_CRT:-./cert/certificate.crt}:/cert/certificate.crt
